/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container': '#ebeef4',
        'surface-container-highest': '#dfe3e8',
        'surface-bright': '#f7f9ff',
        'tertiary-container': '#755900',
        'on-primary-fixed-variant': '#00513b',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        surface: '#f7f9ff',
        'on-error-container': '#93000a',
        'surface-container-high': '#e5e8ee',
        outline: '#6f7a73',
        'on-surface': '#181c20',
        'primary-fixed': '#9ef4d0',
        'on-tertiary-container': '#ffd15d',
        'on-tertiary-fixed': '#251a00',
        'on-primary-container': '#92e7c3',
        'inverse-primary': '#83d7b4',
        background: '#f7f9ff',
        'on-primary': '#ffffff',
        'secondary-container': '#b6d0ff',
        'on-secondary-fixed': '#001b3d',
        'secondary-fixed-dim': '#aec7f6',
        primary: '#00503a',
        'primary-container': '#006a4e',
        tertiary: '#584200',
        'on-secondary-fixed-variant': '#2d476f',
        'on-tertiary-fixed-variant': '#5a4300',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#3f4944',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#3f5881',
        secondary: '#465f88',
        'tertiary-fixed': '#ffdf98',
        'outline-variant': '#bec9c2',
        'surface-dim': '#d7dae0',
        'inverse-on-surface': '#eef1f7',
        'secondary-fixed': '#d6e3ff',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#046c50',
        'inverse-surface': '#2d3135',
        error: '#ba1a1a',
        'primary-fixed-dim': '#83d7b4',
        'surface-container-low': '#f1f4fa',
        'surface-variant': '#dfe3e8',
        'on-primary-fixed': '#002116',
        'on-background': '#181c20',
        'tertiary-fixed-dim': '#f7be06',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
  corePlugins: {
    preflight: false, // Disable preflight to avoid conflicts with Ant Design
  },
};
